version: '3.7'
services:
  homepage:
    container_name: homepage
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
networks:
  default:
    name: docker_default